import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css"
          rel="stylesheet"
        ></link>
      </Head>

      <div className="text-center">
        <h1>My Image Gallery</h1>
        <hr />
      </div>

      {new Array(14).fill().map((_, index) => {
        return (
          <div className="col-8 mx-auto mb-3" key={index}>
            <Image
              width={1500}
              layout="intrinsic"
              height={1000}
              src={`/images/image${index + 1}.jpg`}
              className="rounded"
              alt=""
            ></Image>
            <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit.</p>
          </div>
        );
      })}
    </div>
  );
}
