/* eslint-disable @next/next/no-img-element */
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import lodash from 'lodash';
import { useEffect, useState } from 'react';
const urls = new Array(20)
  .fill()
  .map((_, index) => index + 1)
  .map((i) => `/images/i${(i + 1) % 20}.jpg`);

export default function Home() {
  const [tagToUse, setTagToUse] = useState('Image');

  const renderImages = () => {
    if (tagToUse === 'Image') {
      return urls.map((url, index) => {
        return (
          <div className="col-4 m-4 mx-auto mb-3 text-center" key={index}>
            <Image
              width={900}
              layout="intrinsic"
              height={600}
              placeholder={'blur'}
              src={url}
              blurDataURL={`/placeholder.webp`}
              className="rounded"
              alt=""
              quality={20}
            ></Image>
            <p>
              <b>{index + 1}.</b> Lorem ipsum dolor sit amet consectetur,
              adipisicing elit.
            </p>
          </div>
        );
      });
    }

    return urls.map((url, index) => {
      return (
        <div className="col-4 m-4 mx-auto mb-3 text-center" key={index}>
          <img src={url} className="img-fluid"></img>
          <p>
            <b>{index + 1}.</b> Lorem ipsum dolor sit amet consectetur,
            adipisicing elit.
          </p>
        </div>
      );
    });
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css"
          rel="stylesheet"
        ></link>
      </Head>

      <div className="text-center">
        <h1>My Image Gallery ( {tagToUse} )</h1>
        <hr />

        <button
          type="button"
          className="btn btn-outline-primary m-2"
          onClick={() => setTagToUse('img')}
        >
          img tag
        </button>
        <button
          type="button"
          className="btn btn-outline-primary m-2"
          onClick={() => setTagToUse('Image')}
        >
          Image Component
        </button>
      </div>

      <div className="row">{renderImages()}</div>
    </div>
  );
}
